kind: "Template"
apiVersion: "v1"
metadata:
  name: nf-e-hmg
  annotations:
    description: "nf-e-hmg"
    tags: "nginx"
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: nfe-frontend-nginx
      namespace: nf-e-hmg
    spec:
      lookupPolicy:
        local: false
  - apiVersion: build.openshift.io/v1
    kind: Build
    metadata:
      name: nfe-frontend-nginx
      namespace: nf-e-hmg
    spec:
      nodeSelector: null
      output:
            to:
              kind: ImageStreamTag
              name: 'nfe-frontend-nginx:latest'
      revision:
            type: Git
      source:
            git:
              ref: master
              uri: 'https://github.com/culturagovbr/nfe-visual'
            type: Git
      strategy:
            dockerStrategy:
              dockerfilePath: .
            type: Docker
      triggeredBy: null    
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: nfe-frontend-nginx
      namespace: nf-e-hmg
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
            name: nfe-frontend-nginx
      strategy:
            activeDeadlineSeconds: 21600
            resources: {}
            rollingParams:
              intervalSeconds: 1
              maxSurge: 25%
              maxUnavailable: 25%
              timeoutSeconds: 600
              updatePeriodSeconds: 1
            type: Rolling
      template:
            metadata:
              labels:
                name: nfe-frontend-nginx
            spec:
              containers:
                - image: nfe-frontend-nginx
                  imagePullPolicy: Always
                  name: nfe-frontend-nginx
                  ports:
                    - containerPort: 8081
                      protocol: TCP
              dnsPolicy: ClusterFirst
              restartPolicy: Always
      test: false
      triggers:
            - type: ConfigChange
            - imageChangeParams:
                automatic: true
                containerNames:
                  - nfe-frontend-nginx
                from:
                  kind: ImageStreamTag
                  name: 'nfe-frontend-nginx:latest'
                  namespace: nf-e-hmg
              type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      name: nfe-frontend-nginx
      namespace: nf-e-hmg
    spec:
      ports:
            - name: ok
              port: 8081
              protocol: TCP
              targetPort: 8081
      selector:
            deploymentconfig: nfe-frontend-nginx
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
            app: nfe-frontend-nginx
      name: nfe-frontend-nginx
      namespace: nf-e-hmg
    spec:
      port:
            targetPort: 8081
      to:
            kind: Service
            name: nfe-frontend-nginx
            weight: 100
    wildcardPolicy: None
